NUM_CLASS_FEATURES = 20
NUM_CLASSES = 2
HIDDEN_DIM = 2*NUM_CLASS_FEATURES
LAYER0_SYNC_LOSS_WEIGHT_PROXY = 1
LAYER2_SYNC_LOSS_WEIGHT_PROXY = 1
LAYER0_SYNC_LOSS_WEIGHT_SHADOW = 1
LAYER2_SYNC_LOSS_WEIGHT_SHADOW = 1
BATCH_SIZE = 1000
TRAIN_TEST_RATIO = 9 / 10
TRAIN_DATA_SIZE = int(BATCH_SIZE * TRAIN_TEST_RATIO)
TARGET_PROXY_RATIO = 1/4 # DONE: Train final proxy model on same number of points as in training
TARGET_TRAIN_DATA_SIZE = int(TRAIN_DATA_SIZE * TARGET_PROXY_RATIO)
ATTACK_TRAIN_DATA_SIZE = TRAIN_DATA_SIZE - TARGET_TRAIN_DATA_SIZE
SHADOW_PROXY_HOLDOFF_RATIO = (1 / 3, 1 / 3) # DONE: Should split also into non-member points for conv training
SHADOW_TRAIN_DATA_SIZE = int(ATTACK_TRAIN_DATA_SIZE * SHADOW_PROXY_HOLDOFF_RATIO[0])
PROXY_TRAIN_DATA_SIZE = int(ATTACK_TRAIN_DATA_SIZE * SHADOW_PROXY_HOLDOFF_RATIO[1])
HOLDOFF_TRAIN_DATA_SIZE = ATTACK_TRAIN_DATA_SIZE - PROXY_TRAIN_DATA_SIZE - SHADOW_TRAIN_DATA_SIZE
FEATURE_STD_RANGE = (0.5, 1.5)
NUM_EPOCHS = 512
NUM_PATIENCE_EPOCHS = 4
NUM_SHADOW_MODELS = 10
MINIBATCH_SIZE = 50
SEEDS = range(1, 10)

VERBOSE_REGULAR_TRAINING = False
VERBOSE_CONVOLUTION_TRAINING = True
SHOW_SHADOW_PROXY_LOSS_GRAPHS = False

DECAY_RATE = 0.9999

#DELETE THIS COMMENT
